### ISSUE TITLE
what wrong with this?

### ISSUE THREAD

**Issue by liamxg** [niemasd/FAVITES-Lite#14]
<img width="815" alt="image" src="https://github.com/niemasd/FAVITES-Lite/assets/46078579/e733bd46-33fd-4396-b832-49186206e9e5">

**Comment by liamxg** [comment]
@niemasd

**Comment by niemasd** [comment]
You need to delete the last `&& \` to actually run the command. But note that the `mv` command will need superuser access (I'm guessing you pulled this from the `Dockerfile`, which assumes superuser access the entire time because of how Docker image building works)

I would suggest first familiarizing yourself with how to use the Unix command line and Linux environments in general, as this type of debugging help is out of the scope of the tool itself (these are questions about how to use the command line in Linux)

**Comment by liamxg** [comment]
Thanks

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
